### ISSUE TITLE
FT-004 - Estilos Primera Sección

### ISSUE THREAD

**Issue by diaslucia** [RumRage/landing-page#11]
## Home primera sección

- Acá podemos usar el mixin text_styling para ahorrarnos unas líneas:
![image](https://github.com/RumRage/landing-page/assets/88150989/c954a65d-3c43-4031-a10f-31e26a3a8c24)

- En la lista podemos omitir el div y ponerle la clase directamente a la lista. Cambiamos la etiqueta a `<ul>`, ya que esta se usa para listas NO ordenadas (sin númeración). Arreglar los estilos porque se van a romper.
![image](https://github.com/RumRage/landing-page/assets/88150989/f121bf5d-0646-4175-b0f9-760639b52078)

- Quitar todos los margin-top, paddings, etc.. y dar el espaciado con gap
![image](https://github.com/RumRage/landing-page/assets/88150989/16f369f8-0d61-4abd-adc4-dd2db1c5913a)
- Podés probar un space-between, around o evenly a ver cuál queda mejor
![image](https://github.com/RumRage/landing-page/assets/88150989/bfb173b1-5058-40de-a8ad-0ec87b28d44a)

- Acordarse de usar los mixins!
![image](https://github.com/RumRage/landing-page/assets/88150989/f29e82b2-4fe3-435a-a778-2a11155c2a10)

**Comment by RumRage** [comment]
Creo que no hice muy bien la versión mobile con el uso de flex-box y gap, veo errores en el slider que no tenía antes... Seguro el finde lo vuelva a revisar y lo pueda resolver pero si no es así te consulto el lunes. Buen finde!
